---
title: "Dataset Preprocessing"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
#Load the dataset
dataset=read.csv("diabetes.csv")
```

Identify any Missing Data Values and replacing them with the mean values of the attribute

```{r}
dataset$Pregnancies = ifelse(is.na(dataset$Pregnancies), ave(dataset$Pregnancies, FUN = function(x) mean(x, na.rm = TRUE )), dataset$Pregnancies)

dataset$Glucose = ifelse(is.na(dataset$Glucose), ave(dataset$Glucose, FUN = function(x) mean(x, na.rm = TRUE )), dataset$Glucose)

dataset$BloodPressure = ifelse(is.na(dataset$BloodPressure), ave(dataset$BloodPressure, FUN = function(x) mean(x, na.rm = TRUE )), dataset$BloodPressure)

dataset$SkinThickness = ifelse(is.na(dataset$SkinThickness), ave(dataset$SkinThickness, FUN = function(x) mean(x, na.rm = TRUE )), dataset$SkinThickness)

dataset$Insulin = ifelse(is.na(dataset$Insulin), ave(dataset$Insulin, FUN = function(x) mean(x, na.rm = TRUE )), dataset$Insulin)

dataset$BMI = ifelse(is.na(dataset$BMI), ave(dataset$BMI, FUN = function(x) mean(x, na.rm = TRUE )), dataset$BMI)

dataset$Diabetes = ifelse(is.na(dataset$Diabetes), ave(dataset$Diabetes, FUN = function(x) mean(x, na.rm = TRUE )), dataset$Diabetes)

dataset$Age = ifelse(is.na(dataset$Age), ave(dataset$Age, FUN = function(x) mean(x, na.rm = TRUE )), dataset$Age)

dataset$Outcome = ifelse(is.na(dataset$Outcome), 0, dataset$Outcome)
```

The Dataset does not contain any type categorical values thus does not require encoding of the values.


Splitting the Dataset into Train and Test Data
```{r}
library(caTools)
set.seed(1)
split=sample.split(dataset$Outcome,SplitRatio = 0.8)
train_data=subset(dataset,split==TRUE)
test_data=subset(dataset,split==FALSE)
```

```{r}
(train_data[0:5,])
```

```{r}
dim(train_data)
dim(test_data)
```

```{r}
train_data[, 1:6] = scale(train_data[, 1:6])
train_data[, 8] = scale(train_data[, 8])
test_data[, 1:6] = scale(test_data[, 1:6])
test_data[, 8] = scale(test_data[, 8])
train_data[1:5,]
```